import { hanken } from "./_utils/fonts";
import Navbar from "./_components/Navbar";
import "./globals.css";

export const metadata = {
	title: "Company Profile",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${hanken.className}`}>
				<Navbar menu={["Home", "Services", "Teams", "About Us"]}>
					{children}
				</Navbar>
			</body>
		</html>
	);
}
